import esbuild from "esbuild";
import process from "process";
import { copyFile } from "fs/promises";
import builtins from "builtin-modules";

// Banner message for the generated/bundled files
const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Determine whether to build for production or development
const prod = (process.argv[2] === "production");

// Get the output directory
const outdir = 'dist';

// manifest.json is not part of the bundle graph, so copy it after every build.
const copyManifest = {
	name: 'copy-manifest',
	setup(build) {
		build.onEnd(() => copyFile('manifest.json', `${outdir}/manifest.json`));
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	// styles.css is a second entry point (rather than a copied asset) so that
	// `npm run dev` watches and rebuilds it too. The object form names the outputs,
	// keeping the results flat in dist/ instead of mirroring src/ and styles/.
	entryPoints: {
		main: "src/main.ts",
		styles: "styles/styles.css"
	},
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minifySyntax: prod, // Enable syntax minification in production
	minifyWhitespace: prod, // Disable whitespace minification
	minifyIdentifiers: prod, // Disable identifier minification
	outdir,
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
	},
	minify: prod,
	treeShaking: prod,
	plugins: [copyManifest],
});

// Rebuild or watch based on the mode
if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
